describe('Event Card', () => {
  before(() => {
    cy.visit('test/EventCard')
  })
  it('renders base version properly', () => {
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="event-card-name"]')
      .should('exist')
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="event-card-address-main"]')
      .should('exist')
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="event-card-address-rest"]')
      .should('exist')
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="event-card-time"]')
      .should('have.length', 1)
  })
  it('renders expanded version properly', () => {
    cy.get('[data-cy="expanded-card"]')
      .find('[data-cy="event-card-name"]')
      .should('have.class', 'text-5xl')
    cy.get('[data-cy="expanded-card"]')
      .find('[data-cy="event-card-address-main"]')
      .should('have.class', 'text-2xl')
    cy.get('[data-cy="expanded-card"]')
      .find('[data-cy="event-card-address-rest"]')
      .should('have.class', 'text-lg')
    cy.get('[data-cy="expanded-card"]')
      .find('[data-cy="event-card-description"]')
      .should('exist')
  })
  it('renders time version properly', () => {
    cy.get('[data-cy="time-card"]')
      .find('[data-cy="event-card-updated"]')
      .should('exist')
  })
})
