describe('Game Card test', () => {
  before(() => {
    cy.visit('test/GameCard')
  })
  it('renders "White Wins" form properly', () => {
    cy.get('[data-cy="game-card-white"]')
      .find('[data-cy="white"]')
      .should('exist')
    cy.get('[data-cy="game-card-white"]')
      .find('[data-cy="black"]')
      .should('exist')
    cy.get('[data-cy="game-card-white"]')
      .find('[data-cy="game-card-komi"]')
      .should('exist')
    cy.get('[data-cy="game-card-white"]')
      .find('[data-cy="game-card-handicap"]')
      .should('exist')
    cy.get('[data-cy="game-card-white"]')
      .find('[data-cy="winner-white"]')
      .should('exist')
  })
  it('renders "Black Wins" form properly', () => {
    cy.get('[data-cy="game-card-black"]')
      .find('[data-cy="winner-black"]')
      .should('exist')
  })
  it('renders "Event Info" form properly', () => {
    cy.get('[data-cy="game-card-event"]')
      .find('[data-cy="event-link"]')
      .should('exist')
      .find('a')
      .contains('Go Event Name')
  })
})
