describe('User Card test', () => {
  before(() => {
    cy.visit('test/UserCard')
  })

  it('renders base form properly', () => {
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="user-card-name"]')
      .should('exist')
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="user-card-rank"]')
      .should('exist')
    cy.get('[data-cy="base-card"]')
      .find('[data-cy="user-card-picture"]')
      .should('exist')
  })
  it('renders marker form properly', () => {
    cy.get('[data-cy="marker-card"]')
      .find('[data-cy="user-card-address"]')
      .should('exist')
    cy.get('[data-cy="marker-card"]')
      .find('[data-cy="user-card-bio"]')
      .should('exist')
    cy.get('[data-cy="marker-card"]')
      .find('[data-cy="user-card-updated"]')
      .should('exist')
  })
  it('renders marker form properly', () => {
    cy.get('[data-cy="attendance-card"]')
      .find('[data-cy="user-card-confirmed"]')
      .should('exist')
      .should('have.class', 'opacity-100')
    cy.get('[data-cy="attendance-card"]')
      .find('[data-cy="user-card-paid"]')
      .should('exist')
      .should('have.class', 'opacity-100')
    cy.get('[data-cy="attendance-card"]')
      .find('[data-cy="user-card-checked_in"]')
      .should('exist')
      .should('have.class', 'opacity-25')
  })
})
